# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key', max_length=4, unique=True, verbose_name='Key')),
                ('key_type', models.CharField(choices=[('not_issued', 'Not Issued'), ('issued', 'Issued'), ('used', 'Used')], default='not_issued', max_length=100, verbose_name='Key type')),
            ],
        ),
    ]
